"""
ws/tower_battle_ws.py
---------------------
WebSocket endpoint for Tower of Trials battles.
URL: ws://localhost:8000/ws/tower/{session_id}

Key difference from regular 3v3:
  - Player fighter HP/energy comes from TowerSession.team (persistent),
    NOT from player_characters in the DB.
  - After the battle, the caller posts to /tower/{session_id}/complete
    with the updated team state — this WS only runs the fight.
  - Enemy team is passed in the start message (already generated by
    GET /tower/{session_id}/floor and stored client-side).

Message protocol:
  Client → { type:"start", enemies:[scaled_char_doc, ...] }
  Server → { type:"state", state:{...} }
  Server → { type:"input_required", ... }
  Client → { type:"action", action, target_index, skill_index }
  Server → { type:"events", events:[...] }
  Server → { type:"state", state:{...} }
  Server → { type:"battle_end", outcome, final_team_state:[...] }
"""

import asyncio
import json
import uuid
from fastapi import APIRouter, WebSocket, WebSocketDisconnect
from bson import ObjectId

from db.mongo import db
from engine.battle_state import BattleState, BattleFighter, ENERGY_ON_DEAL
from engine.turn_engine   import resolve_action, ai_choose_action
from engine.skill_definitions import get_skills_for

router = APIRouter()

AI_ACTION_DELAY = 1.0


# ── Builder — from TowerSession team member dict ──────────────────────────────

def _build_from_session_member(member: dict) -> BattleFighter:
    """
    Build a BattleFighter from a TowerSession team-member dict.
    Uses current_hp/current_energy (persistent across floors), NOT DB values.
    """
    char_name = member["name"]
    rarity    = member.get("rarity", "C")

    skills = get_skills_for(
        char_name    = char_name,
        rarity       = rarity,
        primary_name = member.get("skill_name", "Attack"),
        primary_desc = "",
        primary_mult = 1.0,
    )

    return BattleFighter(
        pc_id       = member["pc_id"],
        char_id     = member["char_id"],
        name        = char_name,
        faction     = member.get("faction", "hero"),
        element     = member.get("element", "Power"),
        rarity      = rarity,
        portrait_id = member.get("portrait_id", ""),
        is_player   = True,
        # ── KEY: use persistent HP, not max ──
        hp          = member["current_hp"],
        max_hp      = member["max_hp"],
        atk         = member.get("current_atk", member.get("max_atk", 100)),
        defense     = member.get("current_def", member.get("base_def", 20)),
        spd         = member.get("current_spd", member.get("base_spd", 5)),
        crit        = member.get("current_crit", member.get("base_crit", 10)),
        evade       = member.get("current_evade", member.get("base_evade", 5)),
        # ── energy: start at battle_start_energy (buff) or 0 ──
        energy      = member.get("battle_start_energy", 0),
        skills      = skills,
        skill_name  = skills[0].name if skills else "Attack",
        skill_desc  = skills[0].desc if skills else "",
        skill_mult  = skills[0].mult if skills else 1.0,
        passive_name= member.get("passive_name", ""),
        is_alive    = member.get("is_alive", True) and member["current_hp"] > 0,
    )


def _build_from_scaled_char(char: dict, is_boss: bool = False) -> BattleFighter:
    """Build an enemy BattleFighter from a scaled char doc."""
    char_name = char.get("name", "Enemy")
    rarity    = char.get("rarity", "R")
    skills    = get_skills_for(
        char_name    = char_name,
        rarity       = rarity,
        primary_name = char.get("skill_name", "Attack"),
        primary_desc = char.get("skill_desc", ""),
        primary_mult = char.get("skill_mult", 1.0),
    )

    return BattleFighter(
        pc_id       = "",
        char_id     = char.get("id", str(char.get("_id", ""))),
        name        = char_name,
        faction     = char.get("faction", "villain"),
        element     = char.get("element", "Power"),
        rarity      = rarity,
        portrait_id = char.get("portrait_id", ""),
        is_player   = False,
        hp          = char["base_hp"],
        max_hp      = char["base_hp"],
        atk         = char["base_atk"],
        defense     = char["base_def"],
        spd         = char["base_spd"],
        crit        = char["base_crit"],
        evade       = char["base_evade"],
        energy      = 0,
        skills      = skills,
        skill_name  = skills[0].name if skills else "Attack",
        skill_desc  = skills[0].desc if skills else "",
        skill_mult  = skills[0].mult if skills else 1.0,
        passive_name= char.get("passive_name", ""),
    )


def _fighter_to_team_update(f: BattleFighter) -> dict:
    """Convert post-battle fighter state back to tower session format."""
    return {
        "pc_id":         f.pc_id,
        "hp":            f.hp,
        "energy":        f.energy,
        "is_alive":      f.is_alive,
    }


# ── WebSocket ─────────────────────────────────────────────────────────────────

@router.websocket("/ws/tower/{session_id}")
async def tower_battle(websocket: WebSocket, session_id: str):
    await websocket.accept()

    try:
        # ── 1. Load session ───────────────────────────────────────────────────
        session = await db.tower_sessions.find_one({"_id": ObjectId(session_id)})
        if not session or session.get("status") != "active":
            await websocket.send_json({"type": "error", "message": "Invalid or inactive session"})
            return

        # ── 2. Wait for start message with enemy team ─────────────────────────
        raw     = await websocket.receive_text()
        req     = json.loads(raw)
        enemies_raw = req.get("enemies", [])
        is_boss     = req.get("is_boss", False)

        # Build fighters from session (persistent HP) and scaled enemies
        alive_members    = [m for m in session["team"] if m.get("is_alive", True) and m["current_hp"] > 0]
        player_fighters  = [_build_from_session_member(m) for m in alive_members]
        enemy_fighters   = [_build_from_scaled_char(e, is_boss) for e in enemies_raw]

        if not player_fighters:
            await websocket.send_json({"type": "error", "message": "No alive fighters"})
            return

        # ── 3. Build battle state ─────────────────────────────────────────────
        state = BattleState(
            battle_id    = str(uuid.uuid4()),
            round        = 1,
            phase        = "player_input",
            player_team  = player_fighters,
            enemy_team   = enemy_fighters,
        )
        state.rebuild_turn_queue()
        await websocket.send_json({"type": "state", "state": state.to_dict()})

        # ── 4. Battle loop (same as regular 3v3) ──────────────────────────────
        skill_index = 0

        while not state.is_over():
            current = state.current_fighter()

            if current is None:
                state.round += 1
                state.rebuild_turn_queue()
                await websocket.send_json({
                    "type": "round_start", "round": state.round, "state": state.to_dict()
                })
                if state.is_over():
                    break
                continue

            actor_team, actor_idx = current
            actor = (state.player_team if actor_team == "player" else state.enemy_team)[actor_idx]

            if not actor.is_alive:
                state.advance_queue()
                continue

            if actor_team == "player":
                # Send input request
                enemy_targets = [
                    {"index": i, "name": f.name, "hp": f.hp, "max_hp": f.max_hp,
                     "element": f.element, "rarity": f.rarity}
                    for i, f in enumerate(state.enemy_team) if f.is_alive
                ]
                ally_targets = [
                    {"index": i, "name": f.name, "hp": f.hp, "max_hp": f.max_hp,
                     "element": f.element, "rarity": f.rarity}
                    for i, f in enumerate(state.player_team) if f.is_alive
                ]
                await websocket.send_json({
                    "type":          "input_required",
                    "actor":         actor.to_dict(),
                    "actor_team":    "player",
                    "actor_index":   actor_idx,
                    "enemy_targets": enemy_targets,
                    "ally_targets":  ally_targets,
                    "skills":        actor.skills_for_client(),
                    "energy":        actor.energy,
                    "floor":         session["current_floor"],
                    "is_boss":       is_boss,
                })

                try:
                    raw_action  = await asyncio.wait_for(websocket.receive_text(), timeout=120.0)
                except asyncio.TimeoutError:
                    await websocket.send_json({"type": "error", "message": "Action timed out"})
                    return

                action_req  = json.loads(raw_action)
                action_type = action_req.get("action", "attack")
                target_idx  = int(action_req.get("target_index", 0))
                skill_index = int(action_req.get("skill_index", 0))

            else:
                await asyncio.sleep(AI_ACTION_DELAY)
                action_type, target_idx = ai_choose_action(actor, state.player_team)
                skill_index = 0
                await websocket.send_json({
                    "type": "enemy_acting", "actor": actor.to_dict(),
                    "actor_index": actor_idx, "action": action_type,
                    "target_index": target_idx,
                })

            state, events = resolve_action(
                state, actor_team, actor_idx, action_type, target_idx,
                skill_index if actor_team == "player" else 0,
            )

            await websocket.send_json({"type": "events", "events": events})
            await websocket.send_json({"type": "state",  "state":  state.to_dict()})

            if state.is_over():
                break

        # ── 5. Battle end — return persistent state update ────────────────────
        # Map pc_id → final fighter state so the REST endpoint can save it
        final_team_state = [_fighter_to_team_update(f) for f in state.player_team]

        await websocket.send_json({
            "type":            "battle_end",
            "outcome":         state.outcome,
            "rounds":          state.round,
            "final_team_state": final_team_state,  # POST this to /tower/{id}/complete
        })

    except WebSocketDisconnect:
        pass
    except Exception as exc:
        try:
            await websocket.send_json({"type": "error", "message": str(exc)})
        except Exception:
            pass
